# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image: gitpod/workspace-rust
tasks:
  - init: echo 'init script' # runs during prebuild
    command: |
      cd src
      cargo build